{
 "title": "Kafka Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Events/Sec",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset[1m]))"
    }
   ]
  },
  {
   "title": "Topic user-approve lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_consumergroup_lag{topic=\"user-approve\",consumergroup=\"user-approval-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "user-approval-service Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(irate(process_cpu_seconds_total{pod_name=~\"user-approval-service-.*\"}[30s]))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(machine_cpu_cores) / 2" }
   ]
  },
  {
   "title": "Istio Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"operation-service\", reporter=\"source\"}[1m]))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(machine_cpu_cores) / 2" }
   ]
  },
  {
   "title": "user-approval-service Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(irate(process_cpu_seconds_total{pod_name=~\"user-approval-service-.*\"}[30s]))"
    }
   ]
  },
  {
   "title": "New create-user Topics / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"user-create\"}[1m]))"
    }
   ]
  },
  {
   "title": "Topic user-create lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_consumergroup_lag{topic=\"user-create\",consumergroup=\"user-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Topic user-approve lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_consumergroup_lag{topic=\"user-approve\",consumergroup=\"user-approval-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Topic user-approve-response lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_consumergroup_lag{topic=\"user-approve-response\",consumergroup=\"user-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Topic user-create-response lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_consumergroup_lag{topic=\"user-create-response\",consumergroup=\"operation-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Topic user-create",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"user-create\"})"
    }
   ]
  },
  {
   "title": "Topic user-approve",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"user-approve\"})"
    }
   ]
  },
  {
   "title": "Topic user-approve-response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"user-approve-response\"})"
    }
   ]
  },
  {
   "title": "Topic user-create-response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"user-create-response\"})"
    }
   ]
  },
  {
   "title": "Kafka Topics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset) by (topic)"
    }
   ]
  }
 ]
}